import type { PropsWithChildren } from 'react'

import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

interface Props extends PropsWithChildren {}

const RootLayout = ({ children }: Readonly<Props>) => {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>{children}</body>
        </html>
    )
}

export default RootLayout
